# Generated by Django 6.1.2 on 2026-10-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('signed_up', 'Signed up'), ('email_verified', 'Verified their email'), ('licence_granted', 'Got a licence'), ('licence_upgraded', 'Upgraded a licence'), ('survey_started', 'Started the survey'), ('page_locked', 'Finished a page'), ('survey_submitted', 'Submitted the survey')], max_length=30)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('channel', models.CharField(choices=[('direct', 'Signed up directly'), ('invite', 'Enterprise invite'), ('code', 'Enterprise join code')], default='direct', max_length=10)),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('page', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['kind', 'occurred_at'], name='funnel_kind_time')],
            },
        ),
    ]
