# Generated by Django 6.1.2 on 2026-10-10 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entitlements', '0001_entitlement'),
        ('survey', '0002_placeholder_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('pages_completed', models.PositiveSmallIntegerField(default=0)),
                ('took_before', models.BooleanField(blank=True, null=True)),
                ('took_before_where', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('possible_repeat', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('entitlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='response', to='entitlements.entitlement')),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='survey.surveyversion')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'draft'), ('submitted_at__isnull', True)), models.Q(('status', 'submitted'), ('submitted_at__isnull', False)), _connector='OR'), name='response_submitted_at_iff_submitted'), models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('account',), name='response_one_open_draft_per_account')],
            },
        ),
    ]
