# Generated by Django 6.1.2 on 2026-10-09 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='accounts.person')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.person'),
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=5)),
                ('value_normalised', models.CharField(max_length=254)),
                ('value_display', models.CharField(max_length=254)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', '-is_primary', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('verified_at__isnull', False)), fields=('kind', 'value_normalised'), name='contactpoint_one_owner_per_verified_value'), models.UniqueConstraint(fields=('account', 'kind', 'value_normalised'), name='contactpoint_no_duplicate_on_account'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('account', 'kind'), name='contactpoint_one_primary_per_kind')],
            },
        ),
    ]
