# Generated by Django 6.1.2 on 2026-10-09 08:25
#
# Data migration. Accounts created before 0002 (the production superuser) have
# no Person and no ContactPoint. Give each one a Person and a primary,
# unverified email ContactPoint so the invariants the new code relies on hold
# for every row. Safe to re-run: it only touches accounts still missing a person.

from django.db import migrations


def backfill(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    Person = apps.get_model("accounts", "Person")
    ContactPoint = apps.get_model("accounts", "ContactPoint")

    for account in Account.objects.filter(person__isnull=True):
        account.person = Person.objects.create()
        account.save(update_fields=["person"])
        ContactPoint.objects.get_or_create(
            account=account,
            kind="email",
            # Same rule as services.normalise_email, inlined so this migration
            # never depends on code that may change later.
            value_normalised=account.email.strip().lower(),
            defaults={"value_display": account.email, "is_primary": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_person_and_contact_points"),
    ]

    operations = [
        # Reverse is a no-op: rolling back 0002 drops the tables anyway.
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
