# Generated by Django 6.1.2 on 2026-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_allauth_email_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='personal_email_prompt_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
