# Generated by Django 6.1.2 on 2026-10-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_personal_email_prompt_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='anonymised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
