# Generated by Django 6.1.2 on 2026-10-09 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_personal_email_prompt_dismissed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField()),
                ('source', models.CharField(choices=[('purchase', 'Purchase'), ('manual', 'Granted by hand')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='accounts.person')),
            ],
            options={
                'ordering': ['granted_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('tier__gte', 1), ('tier__lte', 3)), name='entitlement_tier_1_to_3')],
            },
        ),
    ]
