# Generated by Django 6.1.2 on 2026-10-09 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('question_count', models.PositiveIntegerField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='survey_version_number_positive')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('min_value', models.PositiveSmallIntegerField(default=1)),
                ('max_value', models.PositiveSmallIntegerField(default=4)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('survey_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.surveyversion')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('survey_version', 'position'), name='survey_question_unique_position'), models.CheckConstraint(condition=models.Q(('min_value__lte', models.F('max_value'))), name='survey_question_range_ordered')],
            },
        ),
    ]
